name: Deploy Infrastructure with Terraform on AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=mi-terraform-state-bucket-support" -backend-config="key=terraform/state.tfstate" -backend-config="region=us-east-1"

      - name: Validate Terraform files
        run: terraform validate

      - name: Check Terraform format
        run: terraform fmt -check

      - name: Generate Terraform plan
        run: terraform plan -out=tfplan

      - name: Apply Terraform plan
        if: github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approve tfplan

